# Github workflows 名稱
name: GraphQL-blog CI

# 觸發條件
on:
  # 當 push code 到 master branch 時，這個 workflow 會被觸發
  push:
    branches: ['master']
  # 當 pull_request 到 master branch 時，這個 workflow 會被觸發
  pull_request:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# job(任務)可以有很多個，像是 build 任務、test 任務 ... 等
jobs:
  # job - 測試任務
  test:
    # 運行環境
    runs-on: ubuntu-latest
    # test 這個工作裡的 執行步驟
    steps:
      # 使用別人寫好的 actions
      - uses: actions/checkout@v3
      # 使用別人寫好的 yarn actions
      - name: Yarn CLI
        uses: CultureHQ/actions-yarn@v1.0.1
      # 執行 yarn install 與 yarn test
      - name: yarn install and test
        run: |
          yarn install
          yarn test
